# This is an example docker-compose.yml that shows you how to run the project locally
# It is not meant to be used as is in production
version: "3.7"

services:
  self-sovereign-identity:
    build:
      context: .
      args:
        APP_PUBLIC_URL: ${APP_PUBLIC_URL:?Missing APP_PUBLIC_URL variable}
        EBSI_ENV: ${EBSI_ENV:?Missing EBSI_ENV variable}
        EBSI_DEMONSTRATOR_URL: ${EBSI_DEMONSTRATOR_URL:?Missing EBSI_DEMONSTRATOR_URL variable}
        EBSI_WALLET_WEB_CLIENT_URL: ${EBSI_WALLET_WEB_CLIENT_URL:?Missing EBSI_WALLET_WEB_CLIENT_URL variable}
    image: 305472350643.dkr.ecr.eu-central-1.amazonaws.com/intebsi/self-sovereign-identity_ebsiint-1763-app-jwt_v0.0.1
    environment:
      EBSI_ENV: ${EBSI_ENV:?Missing EBSI_ENV variable}
      APP_ISSUER: ${APP_ISSUER:?Missing APP_ISSUER variable}
      APP_PRIVATE_KEY: ${APP_PRIVATE_KEY:?Missing APP_PRIVATE_KEY variable}
      APP_PORT: ${APP_PORT:?Missing APP_PORT variable}
      APP_PUBLIC_URL: ${APP_PUBLIC_URL:?Missing APP_PUBLIC_URL variable}
      NODE_ENV: ${NODE_ENV:?Missing NODE_ENV variable}
      EBSI_WALLET_API: ${EBSI_WALLET_API:?Missing EBSI_WALLET_API variable}
      EBSI_WALLET_WEB_CLIENT_URL: ${EBSI_WALLET_WEB_CLIENT_URL:?Missing EBSI_WALLET_WEB_CLIENT_URL variable}
      LOG_LEVEL: ${LOG_LEVEL:?Missing LOG_LEVEL variable}
    ports:
      - "${APP_PORT}:${APP_PORT}"
